steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wedding-backend:$COMMIT_SHA', '.']

images:
  - 'gcr.io/$PROJECT_ID/wedding-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY